# Generated by Django 3.0.6 on 2020-05-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='slug',
            new_name='user_slug',
        ),
    ]
