# Generated by Django 3.0.6 on 2020-05-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200529_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_slug',
        ),
    ]
