# Generated by Django 3.0.8 on 2020-07-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200715_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('', 'Not Specified'), ('male', 'Male'), ('female', 'Female')], default='', max_length=20, verbose_name='Gender'),
        ),
    ]
