# Generated by Django 3.0.8 on 2020-07-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200716_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('', 'Not Specified'), ('Male', 'Male'), ('Female', 'Female')], default='', max_length=20, verbose_name='Gender'),
        ),
    ]
