# Generated by Django 3.0.8 on 2020-07-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200717_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('', 'Not Specified'), ('Male', 'Male'), ('Female', 'Female')], default='', max_length=50, verbose_name='Gender'),
        ),
    ]
