# Generated by Django 3.0.8 on 2020-09-14 09:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frilium_thread', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicPrivate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_owner', models.BooleanField(default=False)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_topics', to='frilium_thread.Topic')),
            ],
            options={
                'verbose_name': 'private thread',
                'verbose_name_plural': 'private topics',
            },
        ),
    ]
