# Generated by Django 3.0.8 on 2020-09-14 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('private', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicprivate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
