# Generated by Django 3.0.8 on 2020-09-14 09:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frilium_post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.TextField(blank=True, verbose_name='What would you like to report?')),
                ('reason', models.CharField(choices=[('', 'Select a reason'), ('Abuse', 'Abuse'), ('Spam', 'Spam'), ('Off Topic', 'Off Topic')], default='', max_length=50, verbose_name='reason')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frilium_post.Post')),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
                'ordering': ['-created_on', '-pk'],
            },
        ),
    ]
