TOPIC_PRIVATE_CATEGORY_PK = 1

# Frilium admin path

FRILIUM_ADMIN_PATH = 'admincp'

CATEGORY_ROOT_LEVEL = 2

FRILIUM_ADMIN_NAMESPACES = ["admin", "frilium:admin"]

FRILIUM_ADMIN_SESSION_EXPIRATION = 60
