# Generated by Django 3.0.8 on 2020-09-14 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frilium_post', '0001_initial'),
        ('frilium_thread', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='frilium_thread.Topic'),
        ),
    ]
