# Generated by Django 3.0.8 on 2021-03-18 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopicPrivate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_owner', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'private topic',
                'verbose_name_plural': 'private topics',
            },
        ),
    ]
