# Generated by Django 3.0.8 on 2020-07-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_post_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
