# Generated by Django 3.0.6 on 2020-05-28 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20200528_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='board',
        ),
    ]
