# Generated by Django 3.0.6 on 2020-05-30 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20200529_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='slug',
            new_name='board_slug',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='slug',
            new_name='post_slug',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='slug',
            new_name='topic_slug',
        ),
    ]
