# Generated by Django 3.0.6 on 2020-05-30 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20200530_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='board_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_slug',
            new_name='slug',
        ),
    ]
