# Generated by Django 3.0.6 on 2020-05-30 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20200530_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slug',
            new_name='post_slug',
        ),
    ]
