# Generated by Django 3.0.6 on 2020-06-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20200619_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'Board', 'verbose_name_plural': 'Boards'},
        ),
    ]
