# Generated by Django 3.0.6 on 2020-06-20 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20200619_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='user',
            new_name='created_by',
        ),
    ]
