# Generated by Django 3.0.6 on 2020-06-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20200621_0112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'created_at', 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
